In [1]:
import pandas as pd
import sqlite3
from pathlib import Path

clean_path = Path("/Users/chowingchan/Desktop/Project/AI-Analytics-Copilot/data/clean")
db_path = Path("/Users/chowingchan/Desktop/Project/AI-Analytics-Copilot/Competitive-Intelligence-Internal-Analytics-System/data/database/thelook_ecommerce.db")

db_path.parent.mkdir(parents=True, exist_ok=True)

conn = sqlite3.connect(db_path)

tables = {
    "distribution_centers": "distribution_centers_clean.csv",
    "events": "events_clean.csv",
    "inventory_items": "inventory_items_clean.csv",
    "order_items": "order_items_clean.csv",
    "orders": "orders_clean.csv",
    "products": "products_clean.csv",
    "users": "users_clean.csv"
}

for table_name, file_name in tables.items():
    df = pd.read_csv(clean_path/file_name)
    df.to_sql(table_name, conn, if_exists="replace", index=False)
    print(f"Loaded {table_name}: {df.shape}")
conn.close()

Loaded distribution_centers: (10, 4)
Loaded events: (2420738, 13)
Loaded inventory_items: (487901, 12)
Loaded order_items: (180952, 12)
Loaded orders: (124923, 9)
Loaded products: (29120, 9)
Loaded users: (100000, 15)

In [2]:
# test

conn = sqlite3.connect(db_path)

pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
""", conn)

                   name
0  distribution_centers
1                events
2       inventory_items
3           order_items
4                orders
5              products
6                 users

In [3]:
pd.read_sql(
"""
SELECT status, COUNT(*) AS order_count
FROM orders
GROUP BY status;
""", conn)

       status  order_count
0   Cancelled        18723
1    Complete        31028
2  Processing        24948
3    Returned        12570
4     Shipped        37654